name: release

on: [release]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup .NET Environment.
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.101'

    - name: Build package for Release.
      run: |
        cd src/
        dotnet pack -c Release
      if: github.event.action == 'published'

    - name: Push package to nuget.
      env:
        NUGET_KEY: ${{ secrets.ASYLGAREEVR_NUGET_KEY }}
      run: dotnet nuget push **/SmartHead.*.nupkg -k $NUGET_KEY -s https://www.nuget.org/api/v2/package --skip-duplicate
      if: github.event.action == 'published'
